<a href="https://colab.research.google.com/github/Abishek302000/ifelse/blob/main/numpy_arthematic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array(9)

print("Print A= ",a)

b=np.array([10,20,30])

print("Print B= ", b)

addition= np.add(a,b)

print("After Addition =", addition)

sub=np.subtract(b,a)

print("After Subtraction =",sub)

mul=np.multiply (a,b)

print("After Multiplcation =",mul)

div=np.divide (b,a)

print("After Division =",div)

div1=np.divide (b,5)

print("After Division =",div1)

Print A=  9
Print B=  [10 20 30]
After Addition = [19 29 39]
After Subtraction = [ 1 11 21]
After Multiplcation = [ 90 180 270]
After Division = [1.11111111 2.22222222 3.33333333]
After Division = [2. 4. 6.]


In [ ]:
#reciprocal

a= np.array([0.25,1.33,1,111])

print(a)

rec=np.reciprocal(a) 
print(rec)

[  0.25   1.33   1.   111.  ]
[4.         0.7518797  1.         0.00900901]


In [ ]:
a=np.array([10,100,1000])

print(a)

pow=np.power(a,2)
print("after ^2 = ", pow)


b=np.array([2,3,1])

pow1=np.power(a,b)
print("after b array elements as ^ = ", pow1)


[  10  100 1000]
after ^2 =  [    100   10000 1000000]
after b array elements as ^ =  [    100 1000000    1000]


In [ ]:
a= np.array ([10,20,30])
b= np.array ([3,5,7])

print("values of A=", a)
print("values of B=", b)

mm=np.mod(a,b)

rm=np.remainder(a,b)

print("values of MOD=", mm)
print("values of REMAINDER=", rm)



values of A= [10 20 30]
values of B= [3 5 7]
values of MOD= [1 0 2]
values of REMAINDER= [1 0 2]


In [ ]:
a=np.array([-5.6j, 0.2j,11, 1+1j])
print(a)

print("real=",np.real(a))

print("imaginary=",np.imag(a))

print("Conjugate=", np.conj(a))

[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]
real= [-0.  0. 11.  1.]
imaginary= [-5.6  0.2  0.   1. ]
Conjugate= [-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


In [ ]:
a=np.array ([1.0,5.3,123,0.56,25.5,32])

print(a)

print("after rounding up=", np.around(a))

print("after rounding up to 1st decimal value =", np.around(a,decimals=1))

[  1.     5.3  123.     0.56  25.5   32.  ]
after rounding up= [  1.   5. 123.   1.  26.  32.]
after rounding up to 1st decimal value = [  1.    5.3 123.    0.6  25.5  32. ]


In [ ]:
a=np.array ([1.0,-5.3,123,-0.56,25.5,32])

print(a)

print('\n')

print(np.floor(a))

print(np.ceil(a))

[  1.    -5.3  123.    -0.56  25.5   32.  ]


[  1.  -6. 123.  -1.  25.  32.]
[  1.  -5. 123.  -0.  26.  32.]
